version: '3'
services:
  asd:
    image: nginx
    volumes:
      - ${WWW_PATH}:/usr/share/nginx/html:ro
      - ./nginx-conf/asd.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
    networks:
      work-net:
        ipv4_address: 172.22.0.51

  'security.lm.local':
    image: nginx
    volumes:
      - ${WWW_PATH}:/usr/share/nginx/html:ro
      - ./nginx-conf/security.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
    networks:
      work-net:
        ipv4_address: 172.22.0.52
  ###########################################################################
  php:
    build: ./php-fpm
    volumes:
      - ${WWW_PATH}:/usr/share/nginx/html
    environment:
      XDEBUG_CONFIG: "remote_host=172.22.0.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=${XDEBUG_SERVER_NAME}"
    networks:
      work-net:
        ipv4_address: 172.22.0.24
    working_dir: /usr/share/nginx/html
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ${DB_DIR}:/var/lib/postgresql/data
    networks:
      work-net:
        ipv4_address: 172.22.0.25
  adminer:
    image: adminer
    restart: always
    networks:
      work-net:
        ipv4_address: 172.22.0.26
  rabbit:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_VHOST: my_vhost
    networks:
      work-net:
        ipv4_address: 172.22.0.27
  redis:
    image: redis
    restart: always
    networks:
      work-net:
        ipv4_address: 172.22.0.28
networks:
  work-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24