version: '3'
services:
  asd:
    image: nginx
    volumes:
      - /home/alexandr/work/slon/html:/usr/share/nginx/html:ro
      - ./asd.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
    networks:
      work-net:
        ipv4_address: 172.21.0.51

  'security.lm.local':
    image: nginx
    volumes:
      - /home/alexandr/work/slon/html:/usr/share/nginx/html:ro
      - ./security.conf:/etc/nginx/nginx.conf:ro
    #ports:
    #  - "80:80"
    environment:
      - NGINX_PORT=80
    depends_on:
      - php
    networks:
      work-net:
        ipv4_address: 172.21.0.52
  ###########################################################################
  php:
    #image: php:7.2-fpm
    build: ./myfpm
    volumes:
      - /home/alexandr/work/slon/html:/usr/share/nginx/html
    environment:
      XDEBUG_CONFIG: "remote_host=172.21.0.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      work-net:
        ipv4_address: 172.21.0.24
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - /home/alexandr/work/slon/pgdata:/var/lib/postgresql/data
    networks:
      work-net:
        ipv4_address: 172.21.0.25
  adminer:
    image: adminer
    restart: always
    networks:
      work-net:
        ipv4_address: 172.21.0.26
networks:
  work-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24